import React, { useEffect, useRef, useState, lazy, Suspense } from 'react';
import { AnimatePresence, motion, MotionConfig, useReducedMotion, useMotionValue, useSpring, useTransform, useScroll, useAnimationControls } from 'motion/react';
import { ArrowUpRight, ArrowRight, ArrowLeft, MagnifyingGlass, Command, List, X, GithubLogo, EnvelopeSimple, Rss, SlidersHorizontal, CaretRight, CircleNotch, GearSix, BookOpen } from '@phosphor-icons/react';
import { asset, PAGES_MODE, RSS_URL, request } from './api';
import GitHubContent from './GitHubContent';
import { RichText } from './Content';
import Admin from './Admin';
import Search from './Search';
import Reveal from './Reveal';
import ProfileTimeline from './ProfileTimeline';
import Knowledge, {DirectionCards} from './Knowledge';
import '@fontsource/barlow-condensed/latin-700.css';
import '@fontsource/ibm-plex-mono/latin-400.css';
const Lab=lazy(()=>import('./Lab'));
const nav=[['works','作品'],['notes','知识与笔记'],['lab','实验室'],['about','关于']];
const fallbackSettings={name:'m0NSYuke',tagline:'从理解 到行动',description:'VLA · WAM · 视频生成',bio:'我关注 VLA、WAM 与视频生成。',github:'',email:'',university:'',major:'',educationPeriod:'',xiaohongshu:''};
const getRoute=()=>window.location.hash.slice(1)||'home';
const formatDate=date=>date.replaceAll('-','.');
function SectionTitle({number,title,subtitle,link}) {return <div className="section-title"><div><span className="section-number mono">{number}</span><h2>{title}</h2></div>{link?<a href={link} className="section-caption mono">{subtitle}<ArrowUpRight size={16}/></a>:<span className="section-caption mono">{subtitle}</span>}</div>;}
function BrandStatement({as:Heading='h2',text}) {
  const signature=!text||['从理解 到行动','从理解，到行动。','PERCEPTION INTO ACTION'].includes(text);
  return <Heading className="brand-statement" aria-label={signature?'从理解到行动':undefined}>{signature?<><span>从理解</span><i className="signature-line" aria-hidden="true"/><span>到行动</span></>:text}</Heading>;
}
function ResearchTopics({text}) {
  const topics=(text||'').split(/\s*[·|]\s*/).filter(Boolean);
  return <p className="hero-topics">{topics.map((topic,index)=><span key={index}>{topic}</span>)}</p>;
}
function Header({route,onSearch,searchRef}) {
  const [menu,setMenu]=useState(false),icon=useAnimationControls(),reduced=useReducedMotion();
  useEffect(()=>setMenu(false),[route]);
  const search=async()=>{if(!reduced)await icon.start({rotate:[0,-20,0],scale:[1,.75,1],transition:{duration:.16,ease:[.65,0,.35,1]}});onSearch();};
  return <header className="site-header"><a href="#" aria-label="m0NSYuke 首页" className="brand"><img src={asset('wycx-logo.png')} alt="WYCX" width="48" height="48"/><span><strong>m0NSYuke</strong><small>W.Y.C.X</small></span></a><nav className={menu?'open':''} aria-label="主导航">{nav.map(([path,label])=><a key={path} href={`#${path}`} className={route.split('/')[0]===path?'active':''}>{label}</a>)}</nav><button ref={searchRef} className="search-trigger" onClick={search} aria-label="搜索网站"><motion.i animate={icon}><MagnifyingGlass size={18}/></motion.i><span><Command size={13}/> K</span></button><button className="menu-trigger" aria-label={menu?'关闭导航':'打开导航'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={24}/>:<List size={24}/>}</button></header>;
}
function Hero({settings,reduced}) {
  const x=useMotionValue(0),y=useMotionValue(0);const sx=useSpring(x,{stiffness:75,damping:22}),sy=useSpring(y,{stiffness:75,damping:22});const rotation=useTransform(sx,[-14,14],[-2,2]);
  return <section className="hero"><div className="masthead"><motion.h1 initial={reduced?false:{opacity:0,y:26}} animate={{opacity:1,y:0}} transition={{duration:.9,ease:[.22,1,.36,1]}}>m0NSYuke</motion.h1></div>
    <div className="hero-intro"><Reveal className="hero-copy"><BrandStatement text={settings.tagline}/><ResearchTopics text={settings.description}/><a className="outline-button" href="#notes">探索知识 <ArrowRight size={20}/></a></Reveal><Reveal className="terminal mono" delay={.1}><p><span>&gt;</span> whoami</p><p>m0NSYuke / learning in public</p><p className="terminal-command"><span>&gt;</span> open ./knowledge</p><span className={`terminal-caret ${reduced?'still':''}`} aria-hidden="true"/></Reveal><div className="hero-art" onPointerMove={e=>{if(reduced||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)/r.width*28);y.set((e.clientY-r.top-r.height/2)/r.height*20);}} onPointerLeave={()=>{x.set(0);y.set(0);}}><motion.img src={asset('hero-sculpture.png')} alt="金色线框扭转雕塑" style={{x:sx,y:sy,rotate:rotation}} animate={reduced?{}:{scale:[1,1.025,1]}} transition={{duration:9,repeat:Infinity,ease:'easeInOut'}}/><span className="art-coordinate mono">x: idea<br/>y: code<br/>z: reality</span></div></div>
  </section>;
}
function ArticleRow({item,large=false}) {return <a className={`article-row ${large?'large':''}`} href={`#article/${item.id}`}><div className="article-thumb"><img src={asset(item.image||'note-wave.png')} alt="" loading="lazy"/></div><div className="article-text"><span className="article-tag mono">{item.tag}</span><h3>{item.title}</h3><p>{item.summary}</p></div><time className="mono" dateTime={item.date}>{formatDate(item.date)}</time><ArrowUpRight className="row-arrow" size={20}/></a>;}
function ContactLinks({settings}) {return <>{settings.xiaohongshu&&<a href={settings.xiaohongshu} target="_blank" rel="noreferrer" className="gold-link"><BookOpen size={19}/> 小红书 <ArrowUpRight size={16}/></a>}{settings.github&&<a href={settings.github} target="_blank" rel="noreferrer" className="gold-link"><GithubLogo size={19}/> GitHub <ArrowUpRight size={16}/></a>}{settings.email&&<a href={`mailto:${settings.email}`} className="gold-link contact-email"><EnvelopeSimple size={19}/> {settings.email}</a>}</>;}
function Home({items,settings,reduced}) {
  const articles=items.filter(i=>i.kind==='article');
  return <>
    <Hero settings={settings} reduced={reduced}/>
    <section className="feature-section">
      <Reveal><SectionTitle number="01" title="研究与学习" subtitle={<>PERCEPTION<br/>INTO ACTION</>}/></Reveal>
      <Reveal as="a" href="#notes" className="feature-image" aria-label="探索研究方向"><img src={asset('featured-morph.png')} alt="金色线框的抽象形态演化"/><span className="feature-hover mono">FOLLOW THE THREAD <ArrowUpRight size={20}/></span></Reveal>
      <DirectionCards items={items}/>
    </section>
    <div className="home-columns">
      <section className="notes-section">
        <Reveal><SectionTitle number="02" title="知识与笔记" subtitle={<>KNOWLEDGE<br/>AND NOTES</>} link="#notes"/></Reveal>
        {articles.slice(0,3).map((item,index)=><Reveal key={item.id} delay={index*.09}><ArticleRow item={item}/></Reveal>)}
        {!articles.length&&<p className="empty-state">新的笔记正在酝酿。</p>}
        <Reveal className="home-framework-note">学习框架已搭好，笔记会在这里持续更新。</Reveal>
      </section>
      <section className="home-about">
        <Reveal><SectionTitle number="03" title="关于我" subtitle={<>MY<br/>JOURNEY</>}/><span className="serif home-about-name">m0NSYuke.</span></Reveal>
        <ProfileTimeline settings={settings} compact/>
        <Reveal className="home-about-links"><a href="#about" className="gold-link">完整介绍 <ArrowUpRight size={18}/></a><div className="home-contact"><ContactLinks settings={settings}/></div></Reveal>
      </section>
    </div>
  </>;
}
function Collection({type,items}) {const [filter,setFilter]=useState('全部'),[query,setQuery]=useState('');const kind=type==='works'?'project':'article';const data=items.filter(i=>i.kind===kind),tags=['全部',...new Set(data.map(i=>i.tag).filter(Boolean))];const filtered=data.filter(i=>(filter==='全部'||i.tag===filter)&&`${i.title} ${i.summary}`.toLowerCase().includes(query.toLowerCase()));return <div className="page-content collection"><a href="#" className="back-link"><ArrowLeft size={18}/> 返回工作台</a><div className="page-heading"><div><span className="eyebrow">{kind==='project'?'SELECTED WORK / IN PROGRESS':'THINKING OUT LOUD'}</span><h1>{kind==='project'?'想法的形状。':'记录，也是一种构建。'}</h1><p>{kind==='project'?'VLA、WAM 与视频生成方向的项目将在这里整理。':'把问题拆开，把过程写下，把知识连接起来。'}</p></div><span className="mono subtle">{String(data.length).padStart(2,'0')} {kind==='project'?'PROJECTS':'NOTES'}</span></div><div className="collection-toolbar"><div className="filter-tabs" aria-label="内容分类">{tags.map(tag=><button key={tag} aria-pressed={filter===tag} className={filter===tag?'active':''} onClick={()=>setFilter(tag)}>{tag}</button>)}</div><label className="inline-search"><MagnifyingGlass size={18}/><input aria-label="搜索当前内容" placeholder="搜索内容…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><AnimatePresence mode="popLayout">{filtered.length?kind==='article'?<motion.div key="articles" className="article-list" layout>{filtered.map(item=><motion.div key={item.id} layout initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><ArticleRow item={item} large/></motion.div>)}</motion.div>:<motion.div key="projects" className="project-grid" layout>{filtered.map((item,index)=><motion.a key={item.id} layout initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{delay:index*.05}} href={`#project/${item.id}`} className="project-card"><div className="project-art"><img src={asset(item.image||'featured-morph.png')} alt=""/><ArrowUpRight size={24}/></div><div className="project-card-meta"><span className="eyebrow">{item.tag} / {formatDate(item.date)}</span><h2>{item.title}</h2><p>{item.summary}</p>{item.sample&&<small className="sample-label">示例内容</small>}</div></motion.a>)}</motion.div>:<motion.div className="empty-state" key="empty" initial={{opacity:0}} animate={{opacity:1}}><h2>{data.length?'还没有匹配的内容。':'项目整理中。'}</h2><p>{data.length?'换一个词，或查看全部内容。':'项目正在整理，后续会在这里分享新的工作。'}</p><button className="text-button" onClick={()=>{setFilter('全部');setQuery('');}}>清除筛选 <ArrowRight size={18}/></button></motion.div>}</AnimatePresence></div>;}
function Reader({item,items}) {const contentRef=useRef(null),[headings,setHeadings]=useState([]);const {scrollYProgress}=useScroll();useEffect(()=>{setHeadings([...contentRef.current?.querySelectorAll('h2,h3')||[]].map(el=>({id:el.id,text:el.textContent})));},[item?.body]);if(!item)return <div className="page-content empty-state"><h1>这篇内容还没有发布。</h1><a className="gold-link" href="#notes">查看其他笔记 <ArrowRight size={18}/></a></div>;const next=items.filter(i=>i.kind===item.kind&&i.id!==item.id)[0];return <div className="page-content reader"><motion.div className="reading-progress" style={{scaleX:scrollYProgress}}/><a className="back-link" href={item.kind==='article'?'#notes':item.kind==='project'?'#works':'#'}><ArrowLeft size={18}/> {item.kind==='article'?'全部笔记':item.kind==='project'?'全部作品':'返回工作台'}</a><div className="reader-heading"><span className="eyebrow">{item.tag} / {formatDate(item.date)}</span><h1>{item.title}</h1><p>{item.summary}</p>{item.sample&&<span className="sample-label">{item.section==='foundation'?'学习框架示例 · 可继续补充':'示例内容 · 可在后台替换'}</span>}</div>{item.kind==='project'&&item.image&&<div className="reader-art"><motion.img layoutId={item.id==='shape-lab'?'feature-art':undefined} src={asset(item.image)} alt="项目视觉"/></div>}<div className="reading-layout"><article className="prose" ref={contentRef}><RichText content={item.body}/>{item.id==='shape-lab'&&<a className="outline-button" href="#lab">打开实时实验 <SlidersHorizontal size={18}/></a>}</article><aside className="reader-toc"><span className="eyebrow">ON THIS PAGE</span>{headings.map((h,index)=><button key={h.id+index} onClick={()=>document.getElementById(h.id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}>{h.text}</button>)}<a href="#notes">探索更多笔记 <ArrowUpRight size={14}/></a></aside></div>{next&&<a className="next-article" href={`#${next.kind}/${next.id}`}><span className="eyebrow">CONTINUE EXPLORING</span><h2>{next.title}</h2><ArrowRight size={25}/></a>}</div>;}
function About({settings}) {
  return <div className="page-content about-page">
    <a href="#" className="back-link"><ArrowLeft size={18}/> 返回工作台</a>
    <div className="about-grid"><Reveal><span className="eyebrow">THE PERSON BEHIND THE NOTES</span><BrandStatement as="h1" text={settings.tagline}/><p className="about-bio">{settings.bio}</p><span className="mono subtle">VLA / WAM / VIDEO GENERATION</span></Reveal><Reveal as="img" className="about-mark" src={asset('wycx-logo.png')} alt="WYCX 品牌标志" delay={.12}/></div>
    <section className="profile-section"><Reveal><SectionTitle number="01" title="学习轨迹" subtitle="EDUCATION / RESEARCH"/></Reveal><ProfileTimeline settings={settings}/></section>
    <div className="about-values">{[['01','学习','沿着 VLA、WAM 和视频生成，建立自己的知识地图。'],['02','记录','保存论文阅读中的问题、推导与理解。'],['03','探索','把思考带入实践，保留还没有答案的问题。']].map(([num,title,text],index)=><Reveal key={num} delay={index*.1}><span className="mono gold">{num}</span><h2>{title}</h2><p>{text}</p></Reveal>)}</div>
    <Reveal as="section" className="about-contact"><div><span className="eyebrow">LET’S CONNECT</span><h2>让想法发生连接。</h2></div><ContactLinks settings={settings}/></Reveal>
  </div>;
}
function Footer({settings}) {return <footer className="site-footer"><p>保持好奇，继续构建。</p><div><a href={RSS_URL} target="_blank" rel="noreferrer"><Rss size={19}/> RSS</a>{settings.xiaohongshu&&<a href={settings.xiaohongshu} target="_blank" rel="noreferrer"><BookOpen size={19}/> 小红书</a>}{settings.github&&<a href={settings.github} target="_blank" rel="noreferrer"><GithubLogo size={20}/> GitHub</a>}<a href={settings.email?`mailto:${settings.email}`:'#about'}><EnvelopeSimple size={20}/> 联系</a><span className="copyright mono">© m0NSYuke {new Date().getFullYear()}</span><a href="#admin" aria-label="内容管理" className="admin-link"><GearSix size={17}/></a></div></footer>;}
export function App() {
  const [route,setRoute]=useState(getRoute),[data,setData]=useState({items:[],settings:fallbackSettings}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(false);const reduced=useReducedMotion();const searchRef=useRef(null);
  const load=async()=>{try{const result=await request('/api/content');setData(result);setError('');}catch(e){setError(e.message);}finally{setLoading(false);}};
  useEffect(()=>{load();const handler=()=>load();window.addEventListener('focus',handler);const timer=setInterval(()=>{if(!document.hidden)load();},30000);return()=>{window.removeEventListener('focus',handler);clearInterval(timer);};},[]);
  useEffect(()=>{const change=()=>{setRoute(getRoute());window.scrollTo({top:0,behavior:'instant'});};const keys=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(prev=>!prev);}};window.addEventListener('hashchange',change);window.addEventListener('keydown',keys);return()=>{window.removeEventListener('hashchange',change);window.removeEventListener('keydown',keys);};},[]);
  useEffect(()=>{const current=data.items.find(i=>i.id===route.split('/')[1]);document.title=`${current?.title||({home:'个人工作台',works:'作品',notes:'技术笔记',lab:'形态实验',about:'关于',admin:'内容管理'}[route]||'工作台')} — m0NSYuke`;},[route,data.items]);
  const render=()=>{if(route==='admin')return PAGES_MODE?<GitHubContent/>:<Admin onUpdated={load}/>;if(loading)return <div className="page-content loading-state" role="status"><CircleNotch className="spinner" size={28}/> 正在打开工作台…</div>;if(error)return <div className="page-content empty-state" role="alert"><h1>暂时没有连上工作台。</h1><p>{error}</p><button className="outline-button" onClick={()=>{setLoading(true);load();}}>重新加载</button></div>;if(route==='home')return <Home {...data} reduced={reduced}/>;if(route==='notes'||route.startsWith('notes/'))return <Knowledge key={route} items={data.items} topic={route.includes('/')?decodeURIComponent(route.split('/')[1]):'全部'}/>;if(route==='works')return <Collection type={route} items={data.items}/>;if(route==='lab')return <div className="page-content lab-page"><a href="#" className="back-link"><ArrowLeft size={18}/> 返回工作台</a><div className="page-heading"><div><span className="eyebrow">THE LAB / WHERE IDEAS TAKE SHAPE</span><h1>形态实验。</h1><p>把一个参数改变，看看会发生什么。</p></div></div><Suspense fallback={<p className="loading-state">正在准备实验…</p>}><Lab reduced={reduced}/></Suspense><p className="lab-note">没有唯一的正确形态。让直觉与代码，一起找到新的可能。</p></div>;if(route==='about')return <About settings={data.settings}/>;if(/^(article|project|log)\//.test(route))return <Reader item={data.items.find(i=>i.id===route.split('/')[1])} items={data.items}/>;return <div className="page-content empty-state"><h1>这里还没有内容。</h1><a className="gold-link" href="#">回到工作台 <ArrowRight size={18}/></a></div>;};
  return <MotionConfig reducedMotion="user"><a href="#main-content" className="skip-link" onClick={e=>{e.preventDefault();document.querySelector('main')?.focus();}}>跳到主要内容</a><div className="site-shell"><Header route={route} onSearch={()=>setSearch(true)} searchRef={searchRef}/><main id="main-content" tabIndex={-1}><AnimatePresence mode="wait"><motion.div key={route} initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:reduced?0:-5}} transition={{duration:.25}}>{render()}</motion.div></AnimatePresence></main><Footer settings={data.settings}/></div><Search open={search} onClose={()=>setSearch(false)} items={data.items} triggerRef={searchRef}/></MotionConfig>;
}
